miner:
  world:
    blocks:
      - STONE
      - ANDESITE
      - DIORITE
      - GRANITE
    ores:
      COAL_ORE:
        priority: 7
        layer:
          127: 0.01171
      IRON_ORE:
        priority: 6
        layer:
          63: 0.008820
      GOLD_ORE:
        priority: 5
        layer:
          31: 0.001171
      LAPIS_ORE:
        priority: 4
        layer:
          30: 0.001395
      REDSTONE_ORE:
        priority: 3
        layer:
          15: 0.008333
      DIAMOND_ORE:
        priority: 2
        layer:
          15: 0.001395
      EMERALD_ORE:
        priority: 1
        layer:
          64: 0.001395